### ISSUE TITLE
Logout link is not working.

### ISSUE THREAD

**Issue by naveen81** [msalom28/Larasocial#5]
When clicking on that , a popup is coming that says "something is wrong , please try again"

**Comment by msalom28** [comment]
Check your javascript. make sure everything has been loaded properly. Follow the steps for setup.

**Comment by naveen81** [comment]
![image](https://cloud.githubusercontent.com/assets/11977484/11907713/23e801d0-a58b-11e5-826c-12cd40de1ab6.png)


I tried again 
this error is coming..

**Comment by rishirajpurohit** [comment]
yup same error as above

**Comment by chegie** [comment]
I had the same error too. I havent been able to resolve it

**Comment by isubhamb** [comment]
same error

**Comment by ken3d06** [comment]
uncomment <script src="/js/socketio.min.js"></script> in the layouts/default.blade, that should fix it, otherwise in your routes change Route::delete('logout', ['as' => 'logout_path', 'uses' => 'SessionController@destroy']); to Route::get('logout', ['as' => 'logout_path', 'uses' => 'SessionController@destroy']);...should log you out
